name: Node Continuous Integration

on: 
  workflow_dispatch:
    inputs:
      tagid:
        #description: 'Tag ID'
        default: 'JMXData'
        required: true

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: echo "hellow-world" 
     # - run: npm test
     # - run: npm run build
